### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by seanfcarroll** [twilio/twilio-chat-demo-js#15]
See errors in the console below:

<img width="1423" alt="screen shot 2017-01-08 at 18 35 36" src="https://cloud.githubusercontent.com/assets/11340230/21752026/5580695e-d5d1-11e6-8370-0b019a3d5d7e.png">

Possibly related issue: https://github.com/TwilioDevEd/sdk-starter-ruby/issues/2

**Comment by tugis** [comment]
Having the same issue. Any updates here?

**Comment by tugis** [comment]
Found out how to make it work. 

In `public/index.html`, change the `twilio-js` include to: 

`<script src="//media.twiliocdn.com/sdk/js/chat/v0.11/twilio-chat.min.js"></script>`

**Comment by rbeiter** [comment]
Hello @tugis, @seanfcarroll – this is resolved now.  We apologize for the inconvenience.
