### ISSUE TITLE
getUnreadMessagesCount commented out

### ISSUE THREAD

**Issue by guiomie** [twilio/twilio-chat-demo-js#16]
Hi,

Why is the following piece of code commented out? I'm having issues using getUnreadMessagesCount() in my own project and I'm wondering if this function is simply broken?

```
/*
  channel.getUnreadMessagesCount().then(count => {
    if (count > 0) {
      $el.addClass('new-messages');
      $count.text(count);
    }
  });
  */
```

**Comment by uttampanara** [comment]
I have found temp solution for this issue replace getUnreadMessagesCount by getUnconsumedMessagesCount method and it's work

**Comment by guiomie** [comment]
I've tried this function and it also returns 0...
