### ISSUE TITLE
error could not authenticate fpa token

### ISSUE THREAD

**Issue by ReenaPatel2410** [twilio/twilio-chat-demo-js#22]
Error: Could not authenticate fpa token
    at t.<anonymous> (https://media.twiliocdn.com/sdk/js/chat/releases/1.0.1/twilio-chat.min.js:260:18545)
    at r (https://media.twiliocdn.com/sdk/js/chat/releases/1.0.1/twilio-chat.min.js:260:206)
    at Generator.r.213.n [as _invoke] (https://media.twiliocdn.com/sdk/js/chat/releases/1.0.1/twilio-chat.min.js:260:1326)
    at Generator.r.213.e.forEach.e.(anonymous function) [as throw] (https://media.twiliocdn.com/sdk/js/chat/releases/1.0.1/twilio-chat.min.js:260:385)
    at a (https://media.twiliocdn.com/sdk/js/chat/releases/1.0.1/twilio-chat.min.js:260:15551)
    at <anonymous>

after login as guest i got a error

**Comment by d1b1** [comment]
Sample Problem

**Comment by kattybilly** [comment]
+1

**Comment by philnash** [comment]
Hello! I'm a developer evangelist at Twilio. Sorry for taking a while to get to this.

If you are seeing this error it is likely a token problem, which means you may not have set all of your credentials properly in [`credentials.json`](https://github.com/twilio/twilio-chat-demo-js/blob/master/credentials.example.json). Note, you also need to copy `credentials.example.json` to a file called `credentials.json` and then fill it in with your details.

If you have double checked that and are still seeing this issue, please feel free to drop a token that you have created from your app into the comments here and I will take a look.

**Comment by avnishit90** [comment]
this is my fpa token : "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJMTVV5QXFaMDBBUnBYbFRwN2JPNUtMVlA2UjFkVzhrdS0xNTA0NTIwMDE0IiwiZ3JhbnRzIjp7ImlkZW50aXR5Ijoic2ZkZHNmIiwiaXBfbWVzc2FnaW5nIjp7InNlcnZpY2Vfc2lkIjoiU0thNDNmMjRhMjg5MzZkN2U1NDgzZjY2ZDNiY2QwMGMzZCIsImVuZHBvaW50X2lkIjoiU0thNDNmMjRhMjg5MzZkN2U1NDgzZjY2ZDNiY2QwMGMzZHNmZGRzZjg0MTMxMzA4YjIwZDIzN2MyYjY0NzQxZTgzODdhNWQ4IiwicHVzaF9jcmVkZW50aWFsX3NpZCI6IkNSZTljNWVmZjI5ZTc0NDcwOWQ3ZGY4NzVmOGE3OTdiZjAifX0sImlhdCI6MTUwNDUyMDAxNCwiZXhwIjoxNTA0NTYwMDE0LCJpc3MiOiJMTVV5QXFaMDBBUnBYbFRwN2JPNUtMVlA2UjFkVzhrdSIsInN1YiI6IkFDZTE4NWRkOTdmYmNiY2IzOTBhYmQ4NWViYWM5YjQ3OGMifQ.40BpFREQIPfANlMJ9xJLGJ3O5vAfkAmhdOCdZSOlgfE"

and i am getting the following error:

POST https://ems.us1.twilio.com/v1/token 401 (Unauthorized)
twilio-chat.min.js:253 EMS E: Error: The authorization with Token failed
    at t.<anonymous> (https://media.twiliocdn.com/sdk/js/chat/releases/1.0.4/twilio-chat.min.js:253:18457)
    at r (https://media.twiliocdn.com/sdk/js/chat/releases/1.0.4/twilio-chat.min.js:253:206)
    at Generator._invoke (https://media.twiliocdn.com/sdk/js/chat/releases/1.0.4/twilio-chat.min.js:253:1323)
    at Generator.e.(anonymous function) [as throw] (https://media.twiliocdn.com/sdk/js/chat/releases/1.0.4/twilio-chat.min.js:253:385)
    at a (https://media.twiliocdn.com/sdk/js/chat/releases/1.0.4/twilio-chat.min.js:253:15463)

**Comment by philnash** [comment]
Hey @avnishit90, it looks to me like you have your credentials set to the wrong things. You can use a tool like [JWT.io](https://jwt.io/) to unpack the token and inspect the values. For yours, the Service SID appears to actually be a API Key SID. It starts "SK" and I would expect a chat service SID to start "IS". I'm not sure what the SID you have that starts "LM" is, either, I would expect the values for `jti` and `iss` to start with "SK".

So, please make sure you have the right credentials set to the correct values in `credentials.json` and let me know if that solves it.

**Comment by avnishit90** [comment]
I am not able to find "signingKeySid", "signingKeySecret" and "serviceSid"  on my Twilio console. Can you tell me under which section i get these Keys.

**Comment by avnishit90** [comment]
@philnash Thanks for the quick response. I re-created an account and as you said the service sid now starts with 'IS'. I was able to identify the accountSid and serviceSid. However, I am not sure I understand what signingKeySid and signingKeySecret values are supposed to be. I have my 'Auth Token' from my API credentials in Dashboard console of twilio. I am guessing that would be the signingKeySecret. Is my understanding correct? And what would be the signingKeySid? I tried setting it to my accountsid as well as servicesid, however, both of them do not work. Can you please guide me around where I can find these values?

**Comment by avnishit90** [comment]
Hi @philnash , Thanks for guiding me actually, I am missing the step of creating "signingKeySid" and "signingKeySecret".  Thanks for quick response.

**Comment by philnash** [comment]
Hey @avnishit90, the signing key and secret is now known as an API Key and Secret and you can find it under the Tools section in the Chat part of the Twilio Console. Here's a direct link for you though: https://www.twilio.com/console/chat/runtime/api-keys

**Comment by psyferre** [comment]
I ran into this problem as well.  After much troubleshooting (JWT.io showed nothing wrong with my token) I found that the problem was using **"test"** credentials.  Once I switched to the **"production"** version of my chat application's credentials I could authenticate.  That's a pretty big "gotcha".

**Comment by arunicbe** [comment]
I have the same problem. I checked the token with jwt.io. It showed no error. Also, I compared the token generated from my server with the token generated from twilio console ->Testing. The IDs and keys are correct in both token.
