### ISSUE TITLE
Most recent Twilio package is 3.5.0, this demo uses 2.11.1

### ISSUE THREAD

**Issue by Ad-Mora** [twilio/twilio-chat-demo-js#26]
When will this be updated?

**Comment by philnash** [comment]
Good question! I've just made PR #27 to update this repo to use twilio 3.5.0.

If you want to see the differences in how you would achieve this, [check out the diff here](https://github.com/twilio/twilio-chat-demo-js/pull/27/files).

**Comment by philnash** [comment]
This repo is up to version 3.6.5 now.
