### ISSUE TITLE
My bot not enter in chat room

### ISSUE THREAD

**Issue by DanielMaceira** [twilio/twilio-chat-demo-js#29]
I checked out the credentials.json and api.ai integration with Twilio.
The chat work for me as a guest, but bot is not there.

Can you clarify for me?
Thank you!

**Comment by philnash** [comment]
Do you mean this api.ai integration? https://api.ai/docs/integrations/twilio

**Comment by DanielMaceira** [comment]
No! I followed this guide:
https://api.ai/docs/integrations/twilio-programmable-chat

But the bot is not in the chat room, like we see in this tutorial.

**Comment by philnash** [comment]
Ah, my apologies!

Have you double checked that all the credentials are correct and in the correct fields within API.ai as well as your demo application configuration?

Are there any errors in the API.ai console?

**Comment by kkarlallan** [comment]
Same issue here. But I followed mine from this guide coz I'm using Watson Conversation: https://github.com/watson-developer-cloud/botkit-middleware/tree/master/examples/multi-bot

**Comment by dkundel** [comment]
Hey @kkarlallan do you have any specific error messages? Are you testing this on localhost with a tool like [ngrok](https://ngrok.com) or are you running it on a publicly available server?

Cheers,
Dominik

**Comment by kkarlallan** [comment]
Please remove my comment. I found a way for it. Thanks for trying @dkundel . 

Cheer,
Karl

**Comment by dkundel** [comment]
Alright cool! Have a great day!

Cheers,
Dominik

**Comment by philnash** [comment]
Hey @DanielMaceira, I'm going to close this as I haven't heard from your for a while. If you're still having trouble, please open it up again and let me know what's going on.

**Comment by toniGallardo** [comment]
Hi, I follow this tutorial
https://api.ai/docs/integrations/twilio-programmable-chat

But I have the same problem as @DanielMaceira when I start the chat, the bot is not in the chat room as we see in this tutorial.
Thanks!

**Comment by dkundel** [comment]
Hi @toniGallardo! I'm sorry this integration seems to be broken on their side. We tried to tell them multiple times but haven't heard back from them. 
Have you had a look at twilio.com/autopilot? It supports Chat and might be helpful for you. And the [Autopilot CLI](https://www.twilio.com/docs/autopilot/twilio-autopilot-cli) supports pulling in Dialogflow backups from what I know.
