### ISSUE TITLE
getChannelByUniqueName Version 2.1 and 2.0 not working

### ISSUE THREAD

**Issue by mundoon** [twilio/twilio-chat-demo-js#31]
I'm trying to get a channel with getChannelByUniqueName and it does not work.
Return: Can not read property 'getChannelByUniqueName' of undefined...

GetChannelBySid works normally ..

I'm using:
https://media.twiliocdn.com/sdk/js/chat/v2.0/twilio-chat.min.js

`client.getChannelByUniqueName('channel-name').then(function(e){
	            	console.log(e);
	            });`

**Comment by philnash** [comment]
So, the error message says `Can not read property 'getChannelByUniqueName' of undefined` which means that if you are calling `client.getChannelByUniqueName()` then `client` at this point is `undefined`. Can you either share some more code around this or just investigate why `client` isn't defined in your app.

**Comment by abv** [comment]
I ran into the same issue... switched to using https://media.twiliocdn.com/sdk/js/chat/releases/1.2.1/twilio-chat.js and it worked. Maybe it's a bug w/ version 2+ of Twilio's chat lib. Version 2.1 and 2.0 both didn't work. I like you @mundoon am just following the demo / quickstart and running into this.

**Comment by mundoon** [comment]
@philnash  hey man..  the same function using version 1.2.1 works .. I believe it's no problem in my code.

**Comment by beninada** [comment]
I'm running into this same issue with 2.2.0

**Comment by aleksandrsivanovs** [comment]
are you still using `new Client` constructor or factory method `create`?
one of the breaking changes between 1.x and 2.x is full deprecation on constructor, from 2.x going forward you should use the `Client.create` factory to create client: https://www.twilio.com/docs/api/chat/changelogs/javascript#programmable-chat-200-december-1-2017

(and docs for v2.0: http://media.twiliocdn.com/sdk/js/chat/releases/2.0.1/docs/)

**Comment by va-andrew** [comment]
I was having the same issue and the post by @aleksandrsivanovs fixed it for me
