### ISSUE TITLE
Hi i am created the channel and invited other person to chat, my question is how to accept the invitation in android.

### ISSUE THREAD

**Issue by shrishailcne** [twilio/twilio-chat-demo-js#35]

**Comment by ManikandanBalakrishnan** [comment]
I wonder, why no one answered this query? I'm also facing the same issue.

**Comment by berkus** [comment]
@ManikandanBalakrishnan https://media.twiliocdn.com/sdk/android/chat/releases/4.0.3/docs/classcom_1_1twilio_1_1chat_1_1Channel.html#a487a2101d1d9502fa087653d5c4568c3
