### ISSUE TITLE
getMessages() are returning messages that are not allowed

### ISSUE THREAD

**Issue by ylaguna** [twilio/twilio-chat-demo-js#38]
I created a private channel, with a single admin user. Then, I have sent to the same a few messages.

Later, with a simple user without permissions ( just "edit Own Messages"  ). I did the following:

```
chatClient
  .getChannelByUniqueName("privateRoom")
  .then(x => { channel = x }); // I'm  supposed to find the chat? lol
```

then:

`channel.getMessages() -- here I can read ALL messaged even without join the channel`

Am I doing something wrong?

**Comment by ajtack** [comment]
Hi there. That shouldn't be the case, and we just tried locally and failed to reproduce the same. Would you write into Twilio support so we can get some more specific details from you? Ask for me in your request.

We'll comment back in here when we've understood the matter.

**Comment by ylaguna** [comment]
I tried to create a second chat application and now it works perfectly. But I still have the problem at my first _Programmable Chat_

I wil send u guys the ticket

**Comment by ylaguna** [comment]
@ajtack created! My ticket number is #1535005
