### ISSUE TITLE
Conflicting Docs

### ISSUE THREAD

**Issue by sam202020** [twilio/twilio-chat-demo-js#39]
Per https://www.twilio.com/docs/chat/tutorials/chat-application-node-express#initialize-the-programmable-chat-client we initialize the chat client with `new Twilio.Chat.Client(token);`

While per https://www.twilio.com/docs/chat/javascript/changelog#programmable-chat-200-december-1-2017 (from 2017!) the Client construtor is deprecated.

**Comment by berkus** [comment]
Hi!

Thank you! The docs are outdated in places indeed. We will update it asap.

(just in case if you were wondering: `Client` constructor _is_ deprecated and `Client.create` function is the right way to go)

**Comment by sam202020** [comment]
👍
