### ISSUE TITLE
Chat client reinitialize error

### ISSUE THREAD

**Issue by dchennaraidu** [twilio/twilio-chat-demo-js#44]
I have reduced the ttl to 40 seconds **tokenprovider.js**, but on the client side `tokenAboutToExpire` event is never getting hit.

So I have added `tokenExpired` event listener, but unable to update client. (unable to send/retrive messages thereafter)

```
var token = new AccessToken(this.accountSid, this.signingKeySid, this.signingKeySecret, {
    identity: identity,
    ttl: 40
  });
```

**Comment by aleksandrsivanovs** [comment]
Hi!

`tokenAboutToExpire` is emitted roughly 1 minute before the token expiration - hence, if you will use ttl smaller than 1 minute - then it won't fire.
And in general - we don't recommend to use tokens with such small ttl (because of practical reasons).
May I ask why do you need token with ttl 40 seconds?

Aleksandrs

**Comment by dchennaraidu** [comment]
> Hi!
> 
> `tokenAboutToExpire` is emitted roughly 1 minute before the token expiration - hence, if you will use ttl smaller than 1 minute - then it won't fire.
> And in general - we don't recommend to use tokens with such small ttl (because of practical reasons).
> May I ask why do you need token with ttl 40 seconds?
> 
> Aleksandrs

Hi Ivanovs, thanks for the info, and I'm exploring how it works when chat token is expired (so I set 40 to test). 
Now I increased it to 180

![image](https://user-images.githubusercontent.com/12108102/56262582-e914f280-60fc-11e9-8b56-be355f0d15ef.png)

`tokenAboutToExpire`  didn't work, `tokenExpired` worked but even after updating with new token, client is in offline mode

![image](https://user-images.githubusercontent.com/12108102/56262730-9e47aa80-60fd-11e9-9a36-19d21f14ec16.png)

**Comment by dchennaraidu** [comment]
I increased to ttl to 240, `tokenAboutToExpire` is emitted. Thanks for the help @aleksandrsivanovs
