### ISSUE TITLE
updateMemberMessageReadStatus does not work

### ISSUE THREAD

**Issue by dpconstruct** [twilio/twilio-chat-demo-js#51]
updateMemberMessageReadStatus function cannot be called out of anywhere. How should we update our members is not documented.

The following two snippets of codes can be found on your documentation(https://www.twilio.com/docs/chat/consumption-horizon) about updateMemmberMessageReadStatus and the update does not work:

```
activeChannel.on('memberUpdated', function(member) {   
     updateMemberMessageReadStatus(member.identity, 
                                   member.lastConsumedMessageIndex, 
                                   member.lastConsumptionTimestamp);
});

// retrieve the list of members for the active channel
var members = activeChannel.getMembers();
// for each member, set up a listener for when the member is updated
members.then(function(currentMembers) {
    currentMembers.forEach(function(member) {
        // handle the read status information for this member
        // note this method would use the provided information to render
        // this to the user in some way.
        updateMemberMessageReadStatus(
            member.identity, 
            member.lastConsumedMessageIndex, 
            member.lastConsumptionTimestamp
        );
    });
});
```

also raised a ticket in Twilio customer support
ticket number:  4720985

**Comment by philnash** [comment]
Hi @dpconstruct,

You're right, there is no implementation of `updateMemberMessageReadStatus` in this example. As the comment says:

>        // note this method would use the provided information to render
>        // this to the user in some way.

The implementation of `updateMemberMessageReadStatus` is up to you and how you want your application to behave. You may be displaying the member's name alongside the last message they had read and need to move that to appear next to a new message or to the end of the messages. You might just be showing which members haven't caught up yet, or only which members have read everything, so you would need to remove or add a member to that group.

The behaviour of this function is down to your application, so the docs did not implement it.

I'll close this issue, but do re-open it and let me know if you have any further questions. Thanks!
