### ISSUE TITLE
getChannelByUniqueName connects to a different channel as defined

### ISSUE THREAD

**Issue by StarpTech** [twilio/twilio-chat-demo-js#55]
```js
const ch = await client.getChannelByUniqueName('f748d55b-d6d3-4434-8a38-be703a8f049f');
await ch.join()
```

but on every second try, the `channelJoined` event is fired with a different channel. How is that possible? The event for `f748d55b-d6d3-4434-8a38-be703a8f049f` is never fired.

twilio-chat: "^4.1.0"

**Comment by berkus** [comment]
getChannelByXXX is not  joining any channels.

channelJoined is fired for channels you join().

events are asynchronous and may come in any order.

**Comment by StarpTech** [comment]
That's correct but this doesn't describe my issue. Read the issue again.

**Comment by berkus** [comment]
Well, you added a join command, great.

How many other channels are you joined to? What is the ID  of the channel you receive channelJoined for? It it one of the channels you are already joined to or something else?

**Comment by StarpTech** [comment]
> How many other channels are you joined to?

1-2

>  What is the ID of the channel you receive channelJoined for? It it one of the channels you are already joined to or something else?

Yes, it is. 

My point is that after joining X I don't get consistently a `channelJoined` event for X. My workaround is to call `ch.getMessages(30)` after `join()` instead waiting for `channelJoined`.
